apiVersion: v1
kind: Service
metadata:
  name: cloud-build-cicd-service
spec:
  selector:
    app: cloud-build-cicd-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer